/*
Attio Standard Objects

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner{}

// V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner struct for V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner
type V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner struct {
	// A UUID identifying the list that this record is in.
	ListId string `json:"list_id"`
	// A human-readable slug for the list for use in URLs and responses.
	ListApiSlug string `json:"list_api_slug"`
	// A UUID identifying this entry on the list.
	EntryId string `json:"entry_id"`
	// When this entry was created.
	CreatedAt string `json:"created_at"`
}

type _V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner

// NewV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner instantiates a new V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner(listId string, listApiSlug string, entryId string, createdAt string) *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner {
	this := V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner{}
	this.ListId = listId
	this.ListApiSlug = listApiSlug
	this.EntryId = entryId
	this.CreatedAt = createdAt
	return &this
}

// NewV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInnerWithDefaults instantiates a new V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInnerWithDefaults() *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner {
	this := V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner{}
	return &this
}

// GetListId returns the ListId field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetListId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ListId
}

// GetListIdOk returns a tuple with the ListId field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetListIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListId, true
}

// SetListId sets field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) SetListId(v string) {
	o.ListId = v
}

// GetListApiSlug returns the ListApiSlug field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetListApiSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ListApiSlug
}

// GetListApiSlugOk returns a tuple with the ListApiSlug field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetListApiSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListApiSlug, true
}

// SetListApiSlug sets field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) SetListApiSlug(v string) {
	o.ListApiSlug = v
}

// GetEntryId returns the EntryId field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryId, true
}

// SetEntryId sets field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) SetEntryId(v string) {
	o.EntryId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["list_id"] = o.ListId
	toSerialize["list_api_slug"] = o.ListApiSlug
	toSerialize["entry_id"] = o.EntryId
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"list_id",
		"list_api_slug",
		"entry_id",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner := _V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner(varV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner)

	return err
}

type NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner struct {
	value *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner
	isSet bool
}

func (v NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) Get() *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner {
	return v.value
}

func (v *NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) Set(val *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner(val *V2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) *NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner {
	return &NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner{value: val, isSet: true}
}

func (v NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsPeopleRecordsRecordIdEntriesGet200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


