/*
Attio Standard Objects

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2ObjectsDealsRecordsPutRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsDealsRecordsPutRequestData{}

// V2ObjectsDealsRecordsPutRequestData struct for V2ObjectsDealsRecordsPutRequestData
type V2ObjectsDealsRecordsPutRequestData struct {
	Values V2ObjectsDealsRecordsPutRequestDataValues `json:"values"`
	AdditionalProperties map[string]interface{}
}

type _V2ObjectsDealsRecordsPutRequestData V2ObjectsDealsRecordsPutRequestData

// NewV2ObjectsDealsRecordsPutRequestData instantiates a new V2ObjectsDealsRecordsPutRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsDealsRecordsPutRequestData(values V2ObjectsDealsRecordsPutRequestDataValues) *V2ObjectsDealsRecordsPutRequestData {
	this := V2ObjectsDealsRecordsPutRequestData{}
	this.Values = values
	return &this
}

// NewV2ObjectsDealsRecordsPutRequestDataWithDefaults instantiates a new V2ObjectsDealsRecordsPutRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsDealsRecordsPutRequestDataWithDefaults() *V2ObjectsDealsRecordsPutRequestData {
	this := V2ObjectsDealsRecordsPutRequestData{}
	return &this
}

// GetValues returns the Values field value
func (o *V2ObjectsDealsRecordsPutRequestData) GetValues() V2ObjectsDealsRecordsPutRequestDataValues {
	if o == nil {
		var ret V2ObjectsDealsRecordsPutRequestDataValues
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsDealsRecordsPutRequestData) GetValuesOk() (*V2ObjectsDealsRecordsPutRequestDataValues, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Values, true
}

// SetValues sets field value
func (o *V2ObjectsDealsRecordsPutRequestData) SetValues(v V2ObjectsDealsRecordsPutRequestDataValues) {
	o.Values = v
}

func (o V2ObjectsDealsRecordsPutRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsDealsRecordsPutRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["values"] = o.Values

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2ObjectsDealsRecordsPutRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsDealsRecordsPutRequestData := _V2ObjectsDealsRecordsPutRequestData{}

	err = json.Unmarshal(data, &varV2ObjectsDealsRecordsPutRequestData)

	if err != nil {
		return err
	}

	*o = V2ObjectsDealsRecordsPutRequestData(varV2ObjectsDealsRecordsPutRequestData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "values")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2ObjectsDealsRecordsPutRequestData struct {
	value *V2ObjectsDealsRecordsPutRequestData
	isSet bool
}

func (v NullableV2ObjectsDealsRecordsPutRequestData) Get() *V2ObjectsDealsRecordsPutRequestData {
	return v.value
}

func (v *NullableV2ObjectsDealsRecordsPutRequestData) Set(val *V2ObjectsDealsRecordsPutRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsDealsRecordsPutRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsDealsRecordsPutRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsDealsRecordsPutRequestData(val *V2ObjectsDealsRecordsPutRequestData) *NullableV2ObjectsDealsRecordsPutRequestData {
	return &NullableV2ObjectsDealsRecordsPutRequestData{value: val, isSet: true}
}

func (v NullableV2ObjectsDealsRecordsPutRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsDealsRecordsPutRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


