/*
Attio Standard Objects

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf{}

// V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf Sort by attribute
type V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf struct {
	// The direction to sort the results by.
	Direction string `json:"direction"`
	// A slug or ID to identify the attribute to sort by.
	Attribute string `json:"attribute"`
	// Which field on the value to sort by e.g. \"last_name\" on a name value.
	Field *string `json:"field,omitempty"`
}

type _V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf

// NewV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf instantiates a new V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf(direction string, attribute string) *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf {
	this := V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf{}
	this.Direction = direction
	this.Attribute = attribute
	return &this
}

// NewV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOfWithDefaults instantiates a new V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOfWithDefaults() *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf {
	this := V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf{}
	return &this
}

// GetDirection returns the Direction field value
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) SetDirection(v string) {
	o.Direction = v
}

// GetAttribute returns the Attribute field value
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) GetAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribute, true
}

// SetAttribute sets field value
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) SetAttribute(v string) {
	o.Attribute = v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) SetField(v string) {
	o.Field = &v
}

func (o V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["direction"] = o.Direction
	toSerialize["attribute"] = o.Attribute
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	return toSerialize, nil
}

func (o *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"direction",
		"attribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf := _V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf)

	if err != nil {
		return err
	}

	*o = V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf(varV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf)

	return err
}

type NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf struct {
	value *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf
	isSet bool
}

func (v NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) Get() *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf {
	return v.value
}

func (v *NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) Set(val *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf(val *V2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) *NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf {
	return &NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf{value: val, isSet: true}
}

func (v NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsPeopleRecordsQueryPostRequestSortsInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


