/*
Attio Standard Objects

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf{}

// V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf struct for V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf
type V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf struct {
	// A UUID or slug to identify the object that the referenced record belongs to.
	TargetObject string `json:"target_object"`
	// A UUID to identify the referenced record.
	TargetRecordId string `json:"target_record_id"`
	AdditionalProperties map[string]interface{}
}

type _V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf

// NewV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf instantiates a new V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf(targetObject string, targetRecordId string) *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf {
	this := V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf{}
	this.TargetObject = targetObject
	this.TargetRecordId = targetRecordId
	return &this
}

// NewV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOfWithDefaults instantiates a new V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOfWithDefaults() *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf {
	this := V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf{}
	return &this
}

// GetTargetObject returns the TargetObject field value
func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) GetTargetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetObject
}

// GetTargetObjectOk returns a tuple with the TargetObject field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) GetTargetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetObject, true
}

// SetTargetObject sets field value
func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) SetTargetObject(v string) {
	o.TargetObject = v
}

// GetTargetRecordId returns the TargetRecordId field value
func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) GetTargetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetRecordId
}

// GetTargetRecordIdOk returns a tuple with the TargetRecordId field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) GetTargetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetRecordId, true
}

// SetTargetRecordId sets field value
func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) SetTargetRecordId(v string) {
	o.TargetRecordId = v
}

func (o V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target_object"] = o.TargetObject
	toSerialize["target_record_id"] = o.TargetRecordId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target_object",
		"target_record_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf := _V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf{}

	err = json.Unmarshal(data, &varV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf)

	if err != nil {
		return err
	}

	*o = V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf(varV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "target_object")
		delete(additionalProperties, "target_record_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf struct {
	value *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf
	isSet bool
}

func (v NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) Get() *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf {
	return v.value
}

func (v *NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) Set(val *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf(val *V2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) *NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf {
	return &NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf{value: val, isSet: true}
}

func (v NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsPeopleRecordsPutRequestDataValuesCompanyInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


