openapi: 3.1.0
info:
  title: Attio Standard Objects
  version: 2.0.0
servers:
- description: Production
  url: https://api.attio.com
security:
- oauth2: []
paths:
  /v2/objects/people/records/query:
    post:
      description: |-
        Lists person records, with the option to filter and sort results.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: 'List person records '
      tags:
      - People
  /v2/objects/people/records:
    post:
      description: |-
        Creates a new person Record. This endpoint will throw on conflicts of unique attributes, like `email_addresses`. If you would prefer to update person records on conflicts, please use the Assert person record endpoint instead. Please note, the `avatar_url` attribute cannot currently be set via the API.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Create a person Record
      tags:
      - People
    put:
      description: |-
        Use this endpoint to create or update person records, using a unique attribute to search for existing People (for example the `email_addresses` attribute). If a person is found with the same value for the matching attribute, that person will be updated. If no person with the same value for the matching attribute is found, a new person will be created instead. If you would like to avoid matching, please use the Create person endpoint.


        If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Assert a person Record
      tags:
      - People
  /v2/objects/people/records/{record_id}:
    delete:
      description: |-
        Deletes a single person record by ID.

        Required scopes: `object_configuration:read`, `record_permission:read-write`.
      security:
      - oauth2:
        - object_configuration:read
        - record_permission:read-write
      summary: Delete a person Record
      tags:
      - People
    get:
      description: |-
        Gets a single person record by its `record_id`.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: Get a person Record
      tags:
      - People
    patch:
      description: |-
        Use this endpoint to update person records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert person endpoint](/reference/put_v2-objects-people-records) to overwrite or remove multiselect attribute values. Please note, the `avatar_url` attribute cannot currently be updated via the API.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Update a person Record
      tags:
      - People
  /v2/objects/people/records/{record_id}/attributes/{attribute}/values:
    get:
      description: |-
        Gets all values for a given attribute on a person Record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List person record attribute values
      tags:
      - People
  /v2/objects/people/records/{record_id}/entries:
    get:
      description: |-
        List all entries, across all lists, for which this person record is the parent.

        Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
        - list_entry:read
      summary: List person record entries
      tags:
      - People
  /v2/objects/companies/records/query:
    post:
      description: |-
        Lists company records, with the option to filter and sort results.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List company records
      tags:
      - Companies
  /v2/objects/companies/records:
    post:
      description: |-
        Creates a new company record. This endpoint will throw on conflicts of unique attributes, like `domains`. If you would prefer to update company records on conflicts, please use the Assert company record endpoint instead. Please note, the `logo_url` attribute cannot currently be set via the API.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Create a company record
      tags:
      - Companies
    put:
      description: |-
        Use this endpoint to create or update company records, using a unique attribute to search for existing companies (for example, the `domains` attribute). If a company is found with the same value for the matching attribute, that company will be updated. If no company with the same value for the matching attribute is found, a new company will be created instead. If you would like to avoid matching, please use the Create company endpoint.


        If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Assert a company record
      tags:
      - Companies
  /v2/objects/companies/records/{record_id}:
    delete:
      description: |-
        Deletes a single company record by ID.

        Required scopes: `object_configuration:read`, `record_permission:read-write`.
      security:
      - oauth2:
        - object_configuration:read
        - record_permission:read-write
      summary: Delete a company record
      tags:
      - Companies
    get:
      description: |-
        Gets a single company record by its `record_id`.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: Get a company record
      tags:
      - Companies
    patch:
      description: |-
        Use this endpoint to update company records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert company endpoint](/reference/put_v2-objects-companies-records) to overwrite or remove multiselect attribute values. Please note, the `logo_url` attribute cannot currently be updated via the API.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Update a company record
      tags:
      - Companies
  /v2/objects/companies/records/{record_id}/attributes/{attribute}/values:
    get:
      description: |-
        Gets all values for a given attribute on a company record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List company record attribute values
      tags:
      - Companies
  /v2/objects/companies/records/{record_id}/entries:
    get:
      description: |-
        List all entries, across all lists, for which this company record is the parent.

        Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
        - list_entry:read
      summary: List company record entries
      tags:
      - Companies
  /v2/objects/users/records/query:
    post:
      description: |-
        Lists user records, with the option to filter and sort results.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List user records
      tags:
      - Users
  /v2/objects/users/records:
    post:
      description: |-
        Creates a new user record. This endpoint will throw on conflicts of unique attributes, like `primary_email_address`. If you would prefer to update user records on conflicts, please use the Assert user record endpoint instead. Please note, the `avatar_url` attribute cannot currently be set via the API.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Create a user record
      tags:
      - Users
    put:
      description: |-
        Use this endpoint to create or update user records, using a unique attribute to search for existing users (for example the `primary_email_address` attribute). If a user is found with the same value for the matching attribute, that user will be updated, otherwise a new user will be created instead. If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or[...]

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Assert a user record
      tags:
      - Users
  /v2/objects/users/records/{record_id}:
    delete:
      description: |-
        Deletes a single user record by ID.

        Required scopes: `object_configuration:read`, `record_permission:read-write`.
      security:
      - oauth2:
        - object_configuration:read
        - record_permission:read-write
      summary: Delete a user record
      tags:
      - Users
    get:
      description: |-
        Gets a single user record by its `record_id`.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: Get a user record
      tags:
      - Users
    patch:
      description: |-
        Use this endpoint to update user records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert user endpoint](/reference/put_v2-objects-users-records) to overwrite or remove multiselect attribute values. Please note, the `avatar_url` attribute cannot currently be updated via the API.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Update a user Record
      tags:
      - Users
  /v2/objects/users/records/{record_id}/attributes/{attribute}/values:
    get:
      description: |-
        Gets all values for a given attribute on a user record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List user record attribute values
      tags:
      - Users
  /v2/objects/users/records/{record_id}/entries:
    get:
      description: |-
        List all entries, across all lists, for which this user record is the parent.

        Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
        - list_entry:read
      summary: List user record entries
      tags:
      - Users
  /v2/objects/deals/records:
    post:
      description: |-
        Creates a new deal record. This endpoint will throw on conflicts of unique attributes, if defined. If you would prefer to update deal records on conflicts, please use the Assert deal record endpoint instead.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Create a deal record
      tags:
      - Deals
    put:
      description: |-
        Use this endpoint to create or update deal records, using a unique attribute to search for existing deals. By default, deals do not have a unique attribute, so you should add your own attribute with a unique constraint to use this API. If a deal is found with the same value for the matching attribute, that deal will be updated, otherwise a new deal will be created instead. If the matching attribute is a multiselect attribute, new values will be added and existing values will not be delet[...]

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Assert a deal record
      tags:
      - Deals
  /v2/objects/deals/records/{record_id}:
    delete:
      description: |-
        Deletes a single deal record by ID.

        Required scopes: `object_configuration:read`, `record_permission:read-write`.
      security:
      - oauth2:
        - object_configuration:read
        - record_permission:read-write
      summary: Delete a deal record
      tags:
      - Deals
    get:
      description: |-
        Gets a single deal record by its `record_id`.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: Get a deal record
      tags:
      - Deals
    patch:
      description: |-
        Use this endpoint to update deal records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert deal endpoint](/reference/put_v2-objects-deals-records) to overwrite or remove multiselect attribute values.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Update a deal record
      tags:
      - Deals
  /v2/objects/deals/records/{record_id}/attributes/{attribute}/values:
    get:
      description: |-
        Gets all values for a given attribute on a deal record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List deal record attribute values
      tags:
      - Deals
  /v2/objects/deals/records/{record_id}/entries:
    get:
      description: |-
        List all entries, across all lists, for which this deal record is the parent.

        Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
        - list_entry:read
      summary: List deal record entries
      tags:
      - Deals
  /v2/objects/deals/records/query:
    post:
      description: |-
        Lists deal records, with the option to filter and sort results.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List deal records
      tags:
      - Deals
  /v2/objects/workspaces/records:
    post:
      description: |-
        Creates a new workspace record. This endpoint will throw on conflicts of unique attributes, like `workspace_id`. If you would prefer to update workspace records on conflicts, please use the Assert workspace record endpoint instead.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Create a workspace record
      tags:
      - Workspaces
    put:
      description: |-
        Use this endpoint to create or update workspace records, using a unique attribute to search for existing workspaces (for example the `workspace_id` attribute). If a workspace is found with the same value for the matching attribute, that workspace will be updated, otherwise a new workspace will be created instead. If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be e[...]

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Assert a workspace record
      tags:
      - Workspaces
  /v2/objects/workspaces/records/{record_id}:
    delete:
      description: |-
        Deletes a single workspace record by ID.

        Required scopes: `object_configuration:read`, `record_permission:read-write`.
      security:
      - oauth2:
        - object_configuration:read
        - record_permission:read-write
      summary: Delete a workspace record
      tags:
      - Workspaces
    get:
      description: |-
        Gets a single workspace record by its `record_id`.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: Get a workspace record
      tags:
      - Workspaces
    patch:
      description: |-
        Use this endpoint to update workspace records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert workspace endpoint](/reference/put_v2-objects-workspaces-records) to overwrite or remove multiselect attribute values.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
      summary: Update a workspace Record
      tags:
      - Workspaces
  /v2/objects/workspaces/records/{record_id}/attributes/{attribute}/values:
    get:
      description: |-
        Gets all values for a given attribute on a workspace record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List workspace record attribute values
      tags:
      - Workspaces
  /v2/objects/workspaces/records/{record_id}/entries:
    get:
      description: |-
        List all entries, across all lists, for which this workspace record is the parent.

        Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
        - list_entry:read
      summary: List workspace record entries
      tags:
      - Workspaces
  /v2/objects/workspaces/records/query:
    post:
      description: |-
        Lists workspace records, with the option to filter and sort results.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
      summary: List workspace records
      tags:
      - Workspaces
components:
  securitySchemes:
    oauth2:
      description: This API uses OAuth 2.0 with the authorization code grant flow.
      flows:
        authorizationCode:
          authorizationUrl: https://app.attio.com/authorize
          scopes:
            user_management:read: View workspace members.
            user_management:read-write: View workspace members.
            record_permission:read: "View, and optionally write, records."
            record_permission:read-write: "View, and optionally write, records."
            object_configuration:read: "View, and optionally write, the configuration\
              \ and attributes of objects."
            object_configuration:read-write: "View, and optionally write, the configuration\
              \ and attributes of objects."
            list_entry:read: "View, and optionally write, the entries in a list."
            list_entry:read-write: "View, and optionally write, the entries in a list."
            list_configuration:read: "View, and optionally write, the configuration\
              \ and attributes of lists."
            list_configuration:read-write: "View, and optionally write, the configuration\
              \ and attributes of lists."
            public_collection:read: "View, and optionally write, both the settings\
              \ and information within public collections."
            public_collection:read-write: "View, and optionally write, both the settings\
              \ and information within public collections."
            private_collection:read: "View, and optionally modify, both the settings\
              \ and information of all collections within the workspace, regardless\
              \ of their access settings."
            private_collection:read-write: "View, and optionally modify, both the\
              \ settings and information of all collections within the workspace,\
              \ regardless of their access settings."
            comment:read: "View comments (and threads), and optionally write comments."
            comment:read-write: "View comments (and threads), and optionally write\
              \ comments."
            task:read: "View, and optionally write, tasks."
            task:read-write: "View, and optionally write, tasks."
            note:read: "View, and optionally write, notes."
            note:read-write: "View, and optionally write, notes."
            webhook:read: "View, and optionally manage, webhooks."
            webhook:read-write: "View, and optionally manage, webhooks."
          tokenUrl: https://app.attio.com/oauth/token
      type: oauth2