/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ObjectsObjectRecordsPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectRecordsPutRequest{}

// V2ObjectsObjectRecordsPutRequest struct for V2ObjectsObjectRecordsPutRequest
type V2ObjectsObjectRecordsPutRequest struct {
	Data V2ObjectsObjectRecordsPutRequestData `json:"data"`
}

type _V2ObjectsObjectRecordsPutRequest V2ObjectsObjectRecordsPutRequest

// NewV2ObjectsObjectRecordsPutRequest instantiates a new V2ObjectsObjectRecordsPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectRecordsPutRequest(data V2ObjectsObjectRecordsPutRequestData) *V2ObjectsObjectRecordsPutRequest {
	this := V2ObjectsObjectRecordsPutRequest{}
	this.Data = data
	return &this
}

// NewV2ObjectsObjectRecordsPutRequestWithDefaults instantiates a new V2ObjectsObjectRecordsPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectRecordsPutRequestWithDefaults() *V2ObjectsObjectRecordsPutRequest {
	this := V2ObjectsObjectRecordsPutRequest{}
	return &this
}

// GetData returns the Data field value
func (o *V2ObjectsObjectRecordsPutRequest) GetData() V2ObjectsObjectRecordsPutRequestData {
	if o == nil {
		var ret V2ObjectsObjectRecordsPutRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPutRequest) GetDataOk() (*V2ObjectsObjectRecordsPutRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V2ObjectsObjectRecordsPutRequest) SetData(v V2ObjectsObjectRecordsPutRequestData) {
	o.Data = v
}

func (o V2ObjectsObjectRecordsPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectRecordsPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *V2ObjectsObjectRecordsPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsObjectRecordsPutRequest := _V2ObjectsObjectRecordsPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectRecordsPutRequest)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectRecordsPutRequest(varV2ObjectsObjectRecordsPutRequest)

	return err
}

type NullableV2ObjectsObjectRecordsPutRequest struct {
	value *V2ObjectsObjectRecordsPutRequest
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPutRequest) Get() *V2ObjectsObjectRecordsPutRequest {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPutRequest) Set(val *V2ObjectsObjectRecordsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPutRequest(val *V2ObjectsObjectRecordsPutRequest) *NullableV2ObjectsObjectRecordsPutRequest {
	return &NullableV2ObjectsObjectRecordsPutRequest{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


