/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner{}

// V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner struct for V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner
type V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner struct {
	// The spoken text for this segment of the transcript.
	Speech string `json:"speech"`
	// The start time of this speech segment in seconds, measured from the start of the recording.
	StartTime float32 `json:"start_time"`
	// The end time of this speech segment in seconds, measured from the start of the recording.
	EndTime float32 `json:"end_time"`
	Speaker V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerSpeaker `json:"speaker"`
}

type _V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner(speech string, startTime float32, endTime float32, speaker V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerSpeaker) *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner{}
	this.Speech = speech
	this.StartTime = startTime
	this.EndTime = endTime
	this.Speaker = speaker
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerWithDefaults() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner {
	this := V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner{}
	return &this
}

// GetSpeech returns the Speech field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetSpeech() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Speech
}

// GetSpeechOk returns a tuple with the Speech field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetSpeechOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speech, true
}

// SetSpeech sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) SetSpeech(v string) {
	o.Speech = v
}

// GetStartTime returns the StartTime field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetStartTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetStartTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) SetStartTime(v float32) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetEndTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetEndTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) SetEndTime(v float32) {
	o.EndTime = v
}

// GetSpeaker returns the Speaker field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetSpeaker() V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerSpeaker {
	if o == nil {
		var ret V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerSpeaker
		return ret
	}

	return o.Speaker
}

// GetSpeakerOk returns a tuple with the Speaker field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) GetSpeakerOk() (*V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerSpeaker, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speaker, true
}

// SetSpeaker sets field value
func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) SetSpeaker(v V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInnerSpeaker) {
	o.Speaker = v
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["speech"] = o.Speech
	toSerialize["start_time"] = o.StartTime
	toSerialize["end_time"] = o.EndTime
	toSerialize["speaker"] = o.Speaker
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"speech",
		"start_time",
		"end_time",
		"speaker",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner := _V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner(varV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner struct {
	value *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) Get() *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) Set(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner(val *V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner {
	return &NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsCallRecordingIdGet200ResponseDataTranscriptSegmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


