/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId{}

// V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId struct for V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId
type V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId struct {
	// A UUID identifying the workspace this record belongs to.
	WorkspaceId string `json:"workspace_id"`
	// A UUID identifying the object this record belongs to.
	ObjectId string `json:"object_id"`
	// A UUID identifying this record.
	RecordId string `json:"record_id"`
}

type _V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId

// NewV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId instantiates a new V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId(workspaceId string, objectId string, recordId string) *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
	this := V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId{}
	this.WorkspaceId = workspaceId
	this.ObjectId = objectId
	this.RecordId = recordId
	return &this
}

// NewV2ObjectsObjectRecordsQueryPost200ResponseDataInnerIdWithDefaults instantiates a new V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectRecordsQueryPost200ResponseDataInnerIdWithDefaults() *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
	this := V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetObjectId returns the ObjectId field value
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) GetObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) GetObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectId, true
}

// SetObjectId sets field value
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) SetObjectId(v string) {
	o.ObjectId = v
}

// GetRecordId returns the RecordId field value
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) GetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordId, true
}

// SetRecordId sets field value
func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) SetRecordId(v string) {
	o.RecordId = v
}

func (o V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["object_id"] = o.ObjectId
	toSerialize["record_id"] = o.RecordId
	return toSerialize, nil
}

func (o *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_id",
		"object_id",
		"record_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId := _V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId(varV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId)

	return err
}

type NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId struct {
	value *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) Get() *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) Set(val *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId(val *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId {
	return &NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


