/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectViewId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectViewId{}

// ObjectViewId struct for ObjectViewId
type ObjectViewId struct {
	// A UUID identifying the workspace this view belongs to.
	WorkspaceId string `json:"workspace_id"`
	// A UUID identifying the object this view belongs to.
	ObjectId string `json:"object_id"`
	// A UUID identifying this view. Use this value as `filter_view_id` when listing records.
	ViewId string `json:"view_id"`
}

type _ObjectViewId ObjectViewId

// NewObjectViewId instantiates a new ObjectViewId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectViewId(workspaceId string, objectId string, viewId string) *ObjectViewId {
	this := ObjectViewId{}
	this.WorkspaceId = workspaceId
	this.ObjectId = objectId
	this.ViewId = viewId
	return &this
}

// NewObjectViewIdWithDefaults instantiates a new ObjectViewId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectViewIdWithDefaults() *ObjectViewId {
	this := ObjectViewId{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *ObjectViewId) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *ObjectViewId) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *ObjectViewId) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetObjectId returns the ObjectId field value
func (o *ObjectViewId) GetObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value
// and a boolean to check if the value has been set.
func (o *ObjectViewId) GetObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectId, true
}

// SetObjectId sets field value
func (o *ObjectViewId) SetObjectId(v string) {
	o.ObjectId = v
}

// GetViewId returns the ViewId field value
func (o *ObjectViewId) GetViewId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewId
}

// GetViewIdOk returns a tuple with the ViewId field value
// and a boolean to check if the value has been set.
func (o *ObjectViewId) GetViewIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewId, true
}

// SetViewId sets field value
func (o *ObjectViewId) SetViewId(v string) {
	o.ViewId = v
}

func (o ObjectViewId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectViewId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["object_id"] = o.ObjectId
	toSerialize["view_id"] = o.ViewId
	return toSerialize, nil
}

func (o *ObjectViewId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_id",
		"object_id",
		"view_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectViewId := _ObjectViewId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectViewId)

	if err != nil {
		return err
	}

	*o = ObjectViewId(varObjectViewId)

	return err
}

type NullableObjectViewId struct {
	value *ObjectViewId
	isSet bool
}

func (v NullableObjectViewId) Get() *ObjectViewId {
	return v.value
}

func (v *NullableObjectViewId) Set(val *ObjectViewId) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectViewId) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectViewId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectViewId(val *ObjectViewId) *NullableObjectViewId {
	return &NullableObjectViewId{value: val, isSet: true}
}

func (v NullableObjectViewId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectViewId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


