/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsPostRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsPostRequestData{}

// V2MeetingsMeetingIdCallRecordingsPostRequestData struct for V2MeetingsMeetingIdCallRecordingsPostRequestData
type V2MeetingsMeetingIdCallRecordingsPostRequestData struct {
	// A publicly accessible URL to a video file of the call recording. Attio will download the video from this URL asynchronously.  **Requirements:** - **Protocol:** The URL must use the `https` protocol. - **File type:** The file must be a `.mp4` file. - **File size:** The file must not exceed 500MB in size. - **Accessibility:** For the request to be accepted, the URL must be publicly accessible. Attio will make a `HEAD` request to the URL to verify its accessibility and retrieve file metadata. The response to this request must include a `Content-Length` header.
	VideoUrl string `json:"video_url"`
}

type _V2MeetingsMeetingIdCallRecordingsPostRequestData V2MeetingsMeetingIdCallRecordingsPostRequestData

// NewV2MeetingsMeetingIdCallRecordingsPostRequestData instantiates a new V2MeetingsMeetingIdCallRecordingsPostRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsPostRequestData(videoUrl string) *V2MeetingsMeetingIdCallRecordingsPostRequestData {
	this := V2MeetingsMeetingIdCallRecordingsPostRequestData{}
	this.VideoUrl = videoUrl
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsPostRequestDataWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsPostRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsPostRequestDataWithDefaults() *V2MeetingsMeetingIdCallRecordingsPostRequestData {
	this := V2MeetingsMeetingIdCallRecordingsPostRequestData{}
	return &this
}

// GetVideoUrl returns the VideoUrl field value
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestData) GetVideoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestData) GetVideoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VideoUrl, true
}

// SetVideoUrl sets field value
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestData) SetVideoUrl(v string) {
	o.VideoUrl = v
}

func (o V2MeetingsMeetingIdCallRecordingsPostRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsPostRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["video_url"] = o.VideoUrl
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsPostRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"video_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2MeetingsMeetingIdCallRecordingsPostRequestData := _V2MeetingsMeetingIdCallRecordingsPostRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsPostRequestData)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsPostRequestData(varV2MeetingsMeetingIdCallRecordingsPostRequestData)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsPostRequestData struct {
	value *V2MeetingsMeetingIdCallRecordingsPostRequestData
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequestData) Get() *V2MeetingsMeetingIdCallRecordingsPostRequestData {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequestData) Set(val *V2MeetingsMeetingIdCallRecordingsPostRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsPostRequestData(val *V2MeetingsMeetingIdCallRecordingsPostRequestData) *NullableV2MeetingsMeetingIdCallRecordingsPostRequestData {
	return &NullableV2MeetingsMeetingIdCallRecordingsPostRequestData{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


