/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputValueAnyOf16 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputValueAnyOf16{}

// OutputValueAnyOf16 struct for OutputValueAnyOf16
type OutputValueAnyOf16 struct {
	Option SelectOption `json:"option"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _OutputValueAnyOf16 OutputValueAnyOf16

// NewOutputValueAnyOf16 instantiates a new OutputValueAnyOf16 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputValueAnyOf16(option SelectOption, attributeType string) *OutputValueAnyOf16 {
	this := OutputValueAnyOf16{}
	this.Option = option
	this.AttributeType = attributeType
	return &this
}

// NewOutputValueAnyOf16WithDefaults instantiates a new OutputValueAnyOf16 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputValueAnyOf16WithDefaults() *OutputValueAnyOf16 {
	this := OutputValueAnyOf16{}
	return &this
}

// GetOption returns the Option field value
func (o *OutputValueAnyOf16) GetOption() SelectOption {
	if o == nil {
		var ret SelectOption
		return ret
	}

	return o.Option
}

// GetOptionOk returns a tuple with the Option field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf16) GetOptionOk() (*SelectOption, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Option, true
}

// SetOption sets field value
func (o *OutputValueAnyOf16) SetOption(v SelectOption) {
	o.Option = v
}

// GetAttributeType returns the AttributeType field value
func (o *OutputValueAnyOf16) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf16) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *OutputValueAnyOf16) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o OutputValueAnyOf16) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputValueAnyOf16) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["option"] = o.Option
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *OutputValueAnyOf16) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"option",
		"attribute_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputValueAnyOf16 := _OutputValueAnyOf16{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputValueAnyOf16)

	if err != nil {
		return err
	}

	*o = OutputValueAnyOf16(varOutputValueAnyOf16)

	return err
}

type NullableOutputValueAnyOf16 struct {
	value *OutputValueAnyOf16
	isSet bool
}

func (v NullableOutputValueAnyOf16) Get() *OutputValueAnyOf16 {
	return v.value
}

func (v *NullableOutputValueAnyOf16) Set(val *OutputValueAnyOf16) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputValueAnyOf16) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputValueAnyOf16) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputValueAnyOf16(val *OutputValueAnyOf16) *NullableOutputValueAnyOf16 {
	return &NullableOutputValueAnyOf16{value: val, isSet: true}
}

func (v NullableOutputValueAnyOf16) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputValueAnyOf16) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


