/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AttributeId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttributeId{}

// AttributeId struct for AttributeId
type AttributeId struct {
	// A UUID representing the workspace this attribute belongs to.
	WorkspaceId string `json:"workspace_id"`
	// A UUID to identify the object or list that this attribute belongs to
	ObjectId string `json:"object_id"`
	// A UUID to identify this attribute.
	AttributeId string `json:"attribute_id"`
}

type _AttributeId AttributeId

// NewAttributeId instantiates a new AttributeId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributeId(workspaceId string, objectId string, attributeId string) *AttributeId {
	this := AttributeId{}
	this.WorkspaceId = workspaceId
	this.ObjectId = objectId
	this.AttributeId = attributeId
	return &this
}

// NewAttributeIdWithDefaults instantiates a new AttributeId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributeIdWithDefaults() *AttributeId {
	this := AttributeId{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *AttributeId) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *AttributeId) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *AttributeId) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetObjectId returns the ObjectId field value
func (o *AttributeId) GetObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value
// and a boolean to check if the value has been set.
func (o *AttributeId) GetObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectId, true
}

// SetObjectId sets field value
func (o *AttributeId) SetObjectId(v string) {
	o.ObjectId = v
}

// GetAttributeId returns the AttributeId field value
func (o *AttributeId) GetAttributeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeId
}

// GetAttributeIdOk returns a tuple with the AttributeId field value
// and a boolean to check if the value has been set.
func (o *AttributeId) GetAttributeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeId, true
}

// SetAttributeId sets field value
func (o *AttributeId) SetAttributeId(v string) {
	o.AttributeId = v
}

func (o AttributeId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttributeId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["object_id"] = o.ObjectId
	toSerialize["attribute_id"] = o.AttributeId
	return toSerialize, nil
}

func (o *AttributeId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_id",
		"object_id",
		"attribute_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttributeId := _AttributeId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttributeId)

	if err != nil {
		return err
	}

	*o = AttributeId(varAttributeId)

	return err
}

type NullableAttributeId struct {
	value *AttributeId
	isSet bool
}

func (v NullableAttributeId) Get() *AttributeId {
	return v.value
}

func (v *NullableAttributeId) Set(val *AttributeId) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributeId) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributeId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributeId(val *AttributeId) *NullableAttributeId {
	return &NullableAttributeId{value: val, isSet: true}
}

func (v NullableAttributeId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributeId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


