/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ListsPostRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ListsPostRequestData{}

// V2ListsPostRequestData struct for V2ListsPostRequestData
type V2ListsPostRequestData struct {
	// The human-readable name of the list.
	Name string `json:"name"`
	// A unique, human-readable slug to access the list through API calls. Should be formatted in snake case.
	ApiSlug string `json:"api_slug"`
	// A UUID or slug to identify the allowed object type for records added to this list.
	ParentObject string `json:"parent_object"`
	// The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
	WorkspaceAccess NullableString `json:"workspace_access"`
	// The level of access granted to specific workspace members for this list. Pass an empty array to grant access to no workspace members.
	WorkspaceMemberAccess []V2ListsPostRequestDataWorkspaceMemberAccessInner `json:"workspace_member_access"`
}

type _V2ListsPostRequestData V2ListsPostRequestData

// NewV2ListsPostRequestData instantiates a new V2ListsPostRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ListsPostRequestData(name string, apiSlug string, parentObject string, workspaceAccess NullableString, workspaceMemberAccess []V2ListsPostRequestDataWorkspaceMemberAccessInner) *V2ListsPostRequestData {
	this := V2ListsPostRequestData{}
	this.Name = name
	this.ApiSlug = apiSlug
	this.ParentObject = parentObject
	this.WorkspaceAccess = workspaceAccess
	this.WorkspaceMemberAccess = workspaceMemberAccess
	return &this
}

// NewV2ListsPostRequestDataWithDefaults instantiates a new V2ListsPostRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ListsPostRequestDataWithDefaults() *V2ListsPostRequestData {
	this := V2ListsPostRequestData{}
	return &this
}

// GetName returns the Name field value
func (o *V2ListsPostRequestData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V2ListsPostRequestData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V2ListsPostRequestData) SetName(v string) {
	o.Name = v
}

// GetApiSlug returns the ApiSlug field value
func (o *V2ListsPostRequestData) GetApiSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiSlug
}

// GetApiSlugOk returns a tuple with the ApiSlug field value
// and a boolean to check if the value has been set.
func (o *V2ListsPostRequestData) GetApiSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiSlug, true
}

// SetApiSlug sets field value
func (o *V2ListsPostRequestData) SetApiSlug(v string) {
	o.ApiSlug = v
}

// GetParentObject returns the ParentObject field value
func (o *V2ListsPostRequestData) GetParentObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentObject
}

// GetParentObjectOk returns a tuple with the ParentObject field value
// and a boolean to check if the value has been set.
func (o *V2ListsPostRequestData) GetParentObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentObject, true
}

// SetParentObject sets field value
func (o *V2ListsPostRequestData) SetParentObject(v string) {
	o.ParentObject = v
}

// GetWorkspaceAccess returns the WorkspaceAccess field value
// If the value is explicit nil, the zero value for string will be returned
func (o *V2ListsPostRequestData) GetWorkspaceAccess() string {
	if o == nil || o.WorkspaceAccess.Get() == nil {
		var ret string
		return ret
	}

	return *o.WorkspaceAccess.Get()
}

// GetWorkspaceAccessOk returns a tuple with the WorkspaceAccess field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2ListsPostRequestData) GetWorkspaceAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceAccess.Get(), o.WorkspaceAccess.IsSet()
}

// SetWorkspaceAccess sets field value
func (o *V2ListsPostRequestData) SetWorkspaceAccess(v string) {
	o.WorkspaceAccess.Set(&v)
}

// GetWorkspaceMemberAccess returns the WorkspaceMemberAccess field value
func (o *V2ListsPostRequestData) GetWorkspaceMemberAccess() []V2ListsPostRequestDataWorkspaceMemberAccessInner {
	if o == nil {
		var ret []V2ListsPostRequestDataWorkspaceMemberAccessInner
		return ret
	}

	return o.WorkspaceMemberAccess
}

// GetWorkspaceMemberAccessOk returns a tuple with the WorkspaceMemberAccess field value
// and a boolean to check if the value has been set.
func (o *V2ListsPostRequestData) GetWorkspaceMemberAccessOk() ([]V2ListsPostRequestDataWorkspaceMemberAccessInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceMemberAccess, true
}

// SetWorkspaceMemberAccess sets field value
func (o *V2ListsPostRequestData) SetWorkspaceMemberAccess(v []V2ListsPostRequestDataWorkspaceMemberAccessInner) {
	o.WorkspaceMemberAccess = v
}

func (o V2ListsPostRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ListsPostRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["api_slug"] = o.ApiSlug
	toSerialize["parent_object"] = o.ParentObject
	toSerialize["workspace_access"] = o.WorkspaceAccess.Get()
	toSerialize["workspace_member_access"] = o.WorkspaceMemberAccess
	return toSerialize, nil
}

func (o *V2ListsPostRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"api_slug",
		"parent_object",
		"workspace_access",
		"workspace_member_access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ListsPostRequestData := _V2ListsPostRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ListsPostRequestData)

	if err != nil {
		return err
	}

	*o = V2ListsPostRequestData(varV2ListsPostRequestData)

	return err
}

type NullableV2ListsPostRequestData struct {
	value *V2ListsPostRequestData
	isSet bool
}

func (v NullableV2ListsPostRequestData) Get() *V2ListsPostRequestData {
	return v.value
}

func (v *NullableV2ListsPostRequestData) Set(val *V2ListsPostRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ListsPostRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ListsPostRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ListsPostRequestData(val *V2ListsPostRequestData) *NullableV2ListsPostRequestData {
	return &NullableV2ListsPostRequestData{value: val, isSet: true}
}

func (v NullableV2ListsPostRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ListsPostRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


