/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker{}

// V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker struct for V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker
type V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker struct {
	// The name of the speaker.
	Name string `json:"name"`
	// The email address of the speaker.
	EmailAddress *string `json:"email_address,omitempty"`
}

type _V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker

// NewV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker instantiates a new V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker(name string) *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker {
	this := V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker{}
	this.Name = name
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeakerWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeakerWithDefaults() *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker {
	this := V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker{}
	return &this
}

// GetName returns the Name field value
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) SetName(v string) {
	o.Name = v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

func (o V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.EmailAddress) {
		toSerialize["email_address"] = o.EmailAddress
	}
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker := _V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker(varV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker struct {
	value *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) Get() *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) Set(val *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker(val *V2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) *NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker {
	return &NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsPostRequestDataTranscriptInnerSpeaker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


