/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner{}

// V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner struct for V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner
type V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner struct {
	Id V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerId `json:"id"`
	// The status of the call recording. When a call recording is first created, it will have a status of `PROCESSING`. Once the recording is ready, it will transition to `COMPLETED`. If the recording fails for any reason, the status will be `FAILED`.
	Status string `json:"status"`
	// A URL that links directly to the call recording in the Attio web application.
	WebUrl string `json:"web_url"`
	CreatedByActor V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerCreatedByActor `json:"created_by_actor"`
	// The timestamp of when the call recording was created.
	CreatedAt string `json:"created_at"`
}

type _V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner

// NewV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner instantiates a new V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner(id V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerId, status string, webUrl string, createdByActor V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerCreatedByActor, createdAt string) *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner {
	this := V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner{}
	this.Id = id
	this.Status = status
	this.WebUrl = webUrl
	this.CreatedByActor = createdByActor
	this.CreatedAt = createdAt
	return &this
}

// NewV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerWithDefaults instantiates a new V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerWithDefaults() *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner {
	this := V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetId() V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerId {
	if o == nil {
		var ret V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerId
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetIdOk() (*V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) SetId(v V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerId) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) SetStatus(v string) {
	o.Status = v
}

// GetWebUrl returns the WebUrl field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetWebUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebUrl
}

// GetWebUrlOk returns a tuple with the WebUrl field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetWebUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebUrl, true
}

// SetWebUrl sets field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) SetWebUrl(v string) {
	o.WebUrl = v
}

// GetCreatedByActor returns the CreatedByActor field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetCreatedByActor() V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerCreatedByActor {
	if o == nil {
		var ret V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerCreatedByActor
		return ret
	}

	return o.CreatedByActor
}

// GetCreatedByActorOk returns a tuple with the CreatedByActor field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetCreatedByActorOk() (*V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerCreatedByActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByActor, true
}

// SetCreatedByActor sets field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) SetCreatedByActor(v V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInnerCreatedByActor) {
	o.CreatedByActor = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["web_url"] = o.WebUrl
	toSerialize["created_by_actor"] = o.CreatedByActor
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"web_url",
		"created_by_actor",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner := _V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner(varV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner)

	return err
}

type NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner struct {
	value *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner
	isSet bool
}

func (v NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) Get() *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner {
	return v.value
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) Set(val *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner(val *V2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) *NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner {
	return &NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner{value: val, isSet: true}
}

func (v NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsMeetingIdCallRecordingsGet200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


