/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InputValueAnyOf9 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputValueAnyOf9{}

// InputValueAnyOf9 struct for InputValueAnyOf9
type InputValueAnyOf9 struct {
	// The first name.
	FirstName *string `json:"first_name,omitempty"`
	// The last name.
	LastName *string `json:"last_name,omitempty"`
	// The full name.
	FullName *string `json:"full_name,omitempty"`
}

// NewInputValueAnyOf9 instantiates a new InputValueAnyOf9 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputValueAnyOf9() *InputValueAnyOf9 {
	this := InputValueAnyOf9{}
	return &this
}

// NewInputValueAnyOf9WithDefaults instantiates a new InputValueAnyOf9 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputValueAnyOf9WithDefaults() *InputValueAnyOf9 {
	this := InputValueAnyOf9{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *InputValueAnyOf9) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputValueAnyOf9) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *InputValueAnyOf9) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *InputValueAnyOf9) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *InputValueAnyOf9) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputValueAnyOf9) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *InputValueAnyOf9) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *InputValueAnyOf9) SetLastName(v string) {
	o.LastName = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *InputValueAnyOf9) GetFullName() string {
	if o == nil || IsNil(o.FullName) {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputValueAnyOf9) GetFullNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullName) {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *InputValueAnyOf9) HasFullName() bool {
	if o != nil && !IsNil(o.FullName) {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *InputValueAnyOf9) SetFullName(v string) {
	o.FullName = &v
}

func (o InputValueAnyOf9) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputValueAnyOf9) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.FullName) {
		toSerialize["full_name"] = o.FullName
	}
	return toSerialize, nil
}

type NullableInputValueAnyOf9 struct {
	value *InputValueAnyOf9
	isSet bool
}

func (v NullableInputValueAnyOf9) Get() *InputValueAnyOf9 {
	return v.value
}

func (v *NullableInputValueAnyOf9) Set(val *InputValueAnyOf9) {
	v.value = val
	v.isSet = true
}

func (v NullableInputValueAnyOf9) IsSet() bool {
	return v.isSet
}

func (v *NullableInputValueAnyOf9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputValueAnyOf9(val *InputValueAnyOf9) *NullableInputValueAnyOf9 {
	return &NullableInputValueAnyOf9{value: val, isSet: true}
}

func (v NullableInputValueAnyOf9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputValueAnyOf9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


