/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ObjectsObjectViewsGet200ResponsePagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectViewsGet200ResponsePagination{}

// V2ObjectsObjectViewsGet200ResponsePagination struct for V2ObjectsObjectViewsGet200ResponsePagination
type V2ObjectsObjectViewsGet200ResponsePagination struct {
	NextCursor NullableString `json:"next_cursor"`
}

type _V2ObjectsObjectViewsGet200ResponsePagination V2ObjectsObjectViewsGet200ResponsePagination

// NewV2ObjectsObjectViewsGet200ResponsePagination instantiates a new V2ObjectsObjectViewsGet200ResponsePagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectViewsGet200ResponsePagination(nextCursor NullableString) *V2ObjectsObjectViewsGet200ResponsePagination {
	this := V2ObjectsObjectViewsGet200ResponsePagination{}
	this.NextCursor = nextCursor
	return &this
}

// NewV2ObjectsObjectViewsGet200ResponsePaginationWithDefaults instantiates a new V2ObjectsObjectViewsGet200ResponsePagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectViewsGet200ResponsePaginationWithDefaults() *V2ObjectsObjectViewsGet200ResponsePagination {
	this := V2ObjectsObjectViewsGet200ResponsePagination{}
	return &this
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *V2ObjectsObjectViewsGet200ResponsePagination) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2ObjectsObjectViewsGet200ResponsePagination) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *V2ObjectsObjectViewsGet200ResponsePagination) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o V2ObjectsObjectViewsGet200ResponsePagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectViewsGet200ResponsePagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["next_cursor"] = o.NextCursor.Get()
	return toSerialize, nil
}

func (o *V2ObjectsObjectViewsGet200ResponsePagination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ObjectsObjectViewsGet200ResponsePagination := _V2ObjectsObjectViewsGet200ResponsePagination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectViewsGet200ResponsePagination)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectViewsGet200ResponsePagination(varV2ObjectsObjectViewsGet200ResponsePagination)

	return err
}

type NullableV2ObjectsObjectViewsGet200ResponsePagination struct {
	value *V2ObjectsObjectViewsGet200ResponsePagination
	isSet bool
}

func (v NullableV2ObjectsObjectViewsGet200ResponsePagination) Get() *V2ObjectsObjectViewsGet200ResponsePagination {
	return v.value
}

func (v *NullableV2ObjectsObjectViewsGet200ResponsePagination) Set(val *V2ObjectsObjectViewsGet200ResponsePagination) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectViewsGet200ResponsePagination) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectViewsGet200ResponsePagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectViewsGet200ResponsePagination(val *V2ObjectsObjectViewsGet200ResponsePagination) *NullableV2ObjectsObjectViewsGet200ResponsePagination {
	return &NullableV2ObjectsObjectViewsGet200ResponsePagination{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectViewsGet200ResponsePagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectViewsGet200ResponsePagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


