/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkspaceMemberId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceMemberId{}

// WorkspaceMemberId struct for WorkspaceMemberId
type WorkspaceMemberId struct {
	// The ID of the workspace the workspace member belongs to.
	WorkspaceId string `json:"workspace_id"`
	// The ID of the workspace member.
	WorkspaceMemberId string `json:"workspace_member_id"`
}

type _WorkspaceMemberId WorkspaceMemberId

// NewWorkspaceMemberId instantiates a new WorkspaceMemberId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceMemberId(workspaceId string, workspaceMemberId string) *WorkspaceMemberId {
	this := WorkspaceMemberId{}
	this.WorkspaceId = workspaceId
	this.WorkspaceMemberId = workspaceMemberId
	return &this
}

// NewWorkspaceMemberIdWithDefaults instantiates a new WorkspaceMemberId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceMemberIdWithDefaults() *WorkspaceMemberId {
	this := WorkspaceMemberId{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *WorkspaceMemberId) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMemberId) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *WorkspaceMemberId) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetWorkspaceMemberId returns the WorkspaceMemberId field value
func (o *WorkspaceMemberId) GetWorkspaceMemberId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceMemberId
}

// GetWorkspaceMemberIdOk returns a tuple with the WorkspaceMemberId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceMemberId) GetWorkspaceMemberIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceMemberId, true
}

// SetWorkspaceMemberId sets field value
func (o *WorkspaceMemberId) SetWorkspaceMemberId(v string) {
	o.WorkspaceMemberId = v
}

func (o WorkspaceMemberId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceMemberId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["workspace_member_id"] = o.WorkspaceMemberId
	return toSerialize, nil
}

func (o *WorkspaceMemberId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_id",
		"workspace_member_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceMemberId := _WorkspaceMemberId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceMemberId)

	if err != nil {
		return err
	}

	*o = WorkspaceMemberId(varWorkspaceMemberId)

	return err
}

type NullableWorkspaceMemberId struct {
	value *WorkspaceMemberId
	isSet bool
}

func (v NullableWorkspaceMemberId) Get() *WorkspaceMemberId {
	return v.value
}

func (v *NullableWorkspaceMemberId) Set(val *WorkspaceMemberId) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceMemberId) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceMemberId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceMemberId(val *WorkspaceMemberId) *NullableWorkspaceMemberId {
	return &NullableWorkspaceMemberId{value: val, isSet: true}
}

func (v NullableWorkspaceMemberId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceMemberId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


