/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputValueAnyOf12 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputValueAnyOf12{}

// InputValueAnyOf12 struct for InputValueAnyOf12
type InputValueAnyOf12 struct {
	// A number between 0 and 5 (inclusive) to represent a star rating.
	Value float32 `json:"value"`
}

type _InputValueAnyOf12 InputValueAnyOf12

// NewInputValueAnyOf12 instantiates a new InputValueAnyOf12 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputValueAnyOf12(value float32) *InputValueAnyOf12 {
	this := InputValueAnyOf12{}
	this.Value = value
	return &this
}

// NewInputValueAnyOf12WithDefaults instantiates a new InputValueAnyOf12 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputValueAnyOf12WithDefaults() *InputValueAnyOf12 {
	this := InputValueAnyOf12{}
	return &this
}

// GetValue returns the Value field value
func (o *InputValueAnyOf12) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *InputValueAnyOf12) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *InputValueAnyOf12) SetValue(v float32) {
	o.Value = v
}

func (o InputValueAnyOf12) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputValueAnyOf12) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *InputValueAnyOf12) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputValueAnyOf12 := _InputValueAnyOf12{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputValueAnyOf12)

	if err != nil {
		return err
	}

	*o = InputValueAnyOf12(varInputValueAnyOf12)

	return err
}

type NullableInputValueAnyOf12 struct {
	value *InputValueAnyOf12
	isSet bool
}

func (v NullableInputValueAnyOf12) Get() *InputValueAnyOf12 {
	return v.value
}

func (v *NullableInputValueAnyOf12) Set(val *InputValueAnyOf12) {
	v.value = val
	v.isSet = true
}

func (v NullableInputValueAnyOf12) IsSet() bool {
	return v.isSet
}

func (v *NullableInputValueAnyOf12) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputValueAnyOf12(val *InputValueAnyOf12) *NullableInputValueAnyOf12 {
	return &NullableInputValueAnyOf12{value: val, isSet: true}
}

func (v NullableInputValueAnyOf12) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputValueAnyOf12) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


