/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2WebhooksGet200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2WebhooksGet200ResponseDataInner{}

// V2WebhooksGet200ResponseDataInner struct for V2WebhooksGet200ResponseDataInner
type V2WebhooksGet200ResponseDataInner struct {
	// URL where the webhook events will be delivered to.
	TargetUrl string `json:"target_url" validate:"regexp=^https:\\/\\/.*"`
	// One or more events the webhook is subscribed to.
	Subscriptions []V2WebhooksGet200ResponseDataInnerSubscriptionsInner `json:"subscriptions"`
	Id V2WebhooksGet200ResponseDataInnerId `json:"id"`
	// The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
	Status string `json:"status"`
	// When the webhook was created.
	CreatedAt string `json:"created_at"`
}

type _V2WebhooksGet200ResponseDataInner V2WebhooksGet200ResponseDataInner

// NewV2WebhooksGet200ResponseDataInner instantiates a new V2WebhooksGet200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2WebhooksGet200ResponseDataInner(targetUrl string, subscriptions []V2WebhooksGet200ResponseDataInnerSubscriptionsInner, id V2WebhooksGet200ResponseDataInnerId, status string, createdAt string) *V2WebhooksGet200ResponseDataInner {
	this := V2WebhooksGet200ResponseDataInner{}
	this.TargetUrl = targetUrl
	this.Subscriptions = subscriptions
	this.Id = id
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewV2WebhooksGet200ResponseDataInnerWithDefaults instantiates a new V2WebhooksGet200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2WebhooksGet200ResponseDataInnerWithDefaults() *V2WebhooksGet200ResponseDataInner {
	this := V2WebhooksGet200ResponseDataInner{}
	return &this
}

// GetTargetUrl returns the TargetUrl field value
func (o *V2WebhooksGet200ResponseDataInner) GetTargetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetUrl
}

// GetTargetUrlOk returns a tuple with the TargetUrl field value
// and a boolean to check if the value has been set.
func (o *V2WebhooksGet200ResponseDataInner) GetTargetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetUrl, true
}

// SetTargetUrl sets field value
func (o *V2WebhooksGet200ResponseDataInner) SetTargetUrl(v string) {
	o.TargetUrl = v
}

// GetSubscriptions returns the Subscriptions field value
func (o *V2WebhooksGet200ResponseDataInner) GetSubscriptions() []V2WebhooksGet200ResponseDataInnerSubscriptionsInner {
	if o == nil {
		var ret []V2WebhooksGet200ResponseDataInnerSubscriptionsInner
		return ret
	}

	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value
// and a boolean to check if the value has been set.
func (o *V2WebhooksGet200ResponseDataInner) GetSubscriptionsOk() ([]V2WebhooksGet200ResponseDataInnerSubscriptionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subscriptions, true
}

// SetSubscriptions sets field value
func (o *V2WebhooksGet200ResponseDataInner) SetSubscriptions(v []V2WebhooksGet200ResponseDataInnerSubscriptionsInner) {
	o.Subscriptions = v
}

// GetId returns the Id field value
func (o *V2WebhooksGet200ResponseDataInner) GetId() V2WebhooksGet200ResponseDataInnerId {
	if o == nil {
		var ret V2WebhooksGet200ResponseDataInnerId
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V2WebhooksGet200ResponseDataInner) GetIdOk() (*V2WebhooksGet200ResponseDataInnerId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V2WebhooksGet200ResponseDataInner) SetId(v V2WebhooksGet200ResponseDataInnerId) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *V2WebhooksGet200ResponseDataInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V2WebhooksGet200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V2WebhooksGet200ResponseDataInner) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *V2WebhooksGet200ResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *V2WebhooksGet200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *V2WebhooksGet200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o V2WebhooksGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2WebhooksGet200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target_url"] = o.TargetUrl
	toSerialize["subscriptions"] = o.Subscriptions
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *V2WebhooksGet200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target_url",
		"subscriptions",
		"id",
		"status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2WebhooksGet200ResponseDataInner := _V2WebhooksGet200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2WebhooksGet200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = V2WebhooksGet200ResponseDataInner(varV2WebhooksGet200ResponseDataInner)

	return err
}

type NullableV2WebhooksGet200ResponseDataInner struct {
	value *V2WebhooksGet200ResponseDataInner
	isSet bool
}

func (v NullableV2WebhooksGet200ResponseDataInner) Get() *V2WebhooksGet200ResponseDataInner {
	return v.value
}

func (v *NullableV2WebhooksGet200ResponseDataInner) Set(val *V2WebhooksGet200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2WebhooksGet200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2WebhooksGet200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2WebhooksGet200ResponseDataInner(val *V2WebhooksGet200ResponseDataInner) *NullableV2WebhooksGet200ResponseDataInner {
	return &NullableV2WebhooksGet200ResponseDataInner{value: val, isSet: true}
}

func (v NullableV2WebhooksGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2WebhooksGet200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


