/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputValueAnyOf17 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputValueAnyOf17{}

// OutputValueAnyOf17 struct for OutputValueAnyOf17
type OutputValueAnyOf17 struct {
	// A raw text field. Values are limited to 10MB.
	Value string `json:"value"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _OutputValueAnyOf17 OutputValueAnyOf17

// NewOutputValueAnyOf17 instantiates a new OutputValueAnyOf17 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputValueAnyOf17(value string, attributeType string) *OutputValueAnyOf17 {
	this := OutputValueAnyOf17{}
	this.Value = value
	this.AttributeType = attributeType
	return &this
}

// NewOutputValueAnyOf17WithDefaults instantiates a new OutputValueAnyOf17 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputValueAnyOf17WithDefaults() *OutputValueAnyOf17 {
	this := OutputValueAnyOf17{}
	return &this
}

// GetValue returns the Value field value
func (o *OutputValueAnyOf17) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf17) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *OutputValueAnyOf17) SetValue(v string) {
	o.Value = v
}

// GetAttributeType returns the AttributeType field value
func (o *OutputValueAnyOf17) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf17) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *OutputValueAnyOf17) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o OutputValueAnyOf17) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputValueAnyOf17) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *OutputValueAnyOf17) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"attribute_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputValueAnyOf17 := _OutputValueAnyOf17{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputValueAnyOf17)

	if err != nil {
		return err
	}

	*o = OutputValueAnyOf17(varOutputValueAnyOf17)

	return err
}

type NullableOutputValueAnyOf17 struct {
	value *OutputValueAnyOf17
	isSet bool
}

func (v NullableOutputValueAnyOf17) Get() *OutputValueAnyOf17 {
	return v.value
}

func (v *NullableOutputValueAnyOf17) Set(val *OutputValueAnyOf17) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputValueAnyOf17) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputValueAnyOf17) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputValueAnyOf17(val *OutputValueAnyOf17) *NullableOutputValueAnyOf17 {
	return &NullableOutputValueAnyOf17{value: val, isSet: true}
}

func (v NullableOutputValueAnyOf17) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputValueAnyOf17) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


