/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputValueAnyOf8 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputValueAnyOf8{}

// InputValueAnyOf8 struct for InputValueAnyOf8
type InputValueAnyOf8 struct {
	// Numbers are persisted as 64 bit floats.
	Value float32 `json:"value"`
}

type _InputValueAnyOf8 InputValueAnyOf8

// NewInputValueAnyOf8 instantiates a new InputValueAnyOf8 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputValueAnyOf8(value float32) *InputValueAnyOf8 {
	this := InputValueAnyOf8{}
	this.Value = value
	return &this
}

// NewInputValueAnyOf8WithDefaults instantiates a new InputValueAnyOf8 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputValueAnyOf8WithDefaults() *InputValueAnyOf8 {
	this := InputValueAnyOf8{}
	return &this
}

// GetValue returns the Value field value
func (o *InputValueAnyOf8) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *InputValueAnyOf8) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *InputValueAnyOf8) SetValue(v float32) {
	o.Value = v
}

func (o InputValueAnyOf8) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputValueAnyOf8) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *InputValueAnyOf8) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputValueAnyOf8 := _InputValueAnyOf8{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputValueAnyOf8)

	if err != nil {
		return err
	}

	*o = InputValueAnyOf8(varInputValueAnyOf8)

	return err
}

type NullableInputValueAnyOf8 struct {
	value *InputValueAnyOf8
	isSet bool
}

func (v NullableInputValueAnyOf8) Get() *InputValueAnyOf8 {
	return v.value
}

func (v *NullableInputValueAnyOf8) Set(val *InputValueAnyOf8) {
	v.value = val
	v.isSet = true
}

func (v NullableInputValueAnyOf8) IsSet() bool {
	return v.isSet
}

func (v *NullableInputValueAnyOf8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputValueAnyOf8(val *InputValueAnyOf8) *NullableInputValueAnyOf8 {
	return &NullableInputValueAnyOf8{value: val, isSet: true}
}

func (v NullableInputValueAnyOf8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputValueAnyOf8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


