/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputValueAnyOf9 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputValueAnyOf9{}

// OutputValueAnyOf9 struct for OutputValueAnyOf9
type OutputValueAnyOf9 struct {
	// Numbers are persisted as 64 bit floats.
	Value float32 `json:"value"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _OutputValueAnyOf9 OutputValueAnyOf9

// NewOutputValueAnyOf9 instantiates a new OutputValueAnyOf9 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputValueAnyOf9(value float32, attributeType string) *OutputValueAnyOf9 {
	this := OutputValueAnyOf9{}
	this.Value = value
	this.AttributeType = attributeType
	return &this
}

// NewOutputValueAnyOf9WithDefaults instantiates a new OutputValueAnyOf9 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputValueAnyOf9WithDefaults() *OutputValueAnyOf9 {
	this := OutputValueAnyOf9{}
	return &this
}

// GetValue returns the Value field value
func (o *OutputValueAnyOf9) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf9) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *OutputValueAnyOf9) SetValue(v float32) {
	o.Value = v
}

// GetAttributeType returns the AttributeType field value
func (o *OutputValueAnyOf9) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf9) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *OutputValueAnyOf9) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o OutputValueAnyOf9) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputValueAnyOf9) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *OutputValueAnyOf9) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"attribute_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputValueAnyOf9 := _OutputValueAnyOf9{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputValueAnyOf9)

	if err != nil {
		return err
	}

	*o = OutputValueAnyOf9(varOutputValueAnyOf9)

	return err
}

type NullableOutputValueAnyOf9 struct {
	value *OutputValueAnyOf9
	isSet bool
}

func (v NullableOutputValueAnyOf9) Get() *OutputValueAnyOf9 {
	return v.value
}

func (v *NullableOutputValueAnyOf9) Set(val *OutputValueAnyOf9) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputValueAnyOf9) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputValueAnyOf9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputValueAnyOf9(val *OutputValueAnyOf9) *NullableOutputValueAnyOf9 {
	return &NullableOutputValueAnyOf9{value: val, isSet: true}
}

func (v NullableOutputValueAnyOf9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputValueAnyOf9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


