/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputValueAnyOf12 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputValueAnyOf12{}

// OutputValueAnyOf12 struct for OutputValueAnyOf12
type OutputValueAnyOf12 struct {
	// The UUID identifying the selected status.
	Status string `json:"status"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _OutputValueAnyOf12 OutputValueAnyOf12

// NewOutputValueAnyOf12 instantiates a new OutputValueAnyOf12 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputValueAnyOf12(status string, attributeType string) *OutputValueAnyOf12 {
	this := OutputValueAnyOf12{}
	this.Status = status
	this.AttributeType = attributeType
	return &this
}

// NewOutputValueAnyOf12WithDefaults instantiates a new OutputValueAnyOf12 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputValueAnyOf12WithDefaults() *OutputValueAnyOf12 {
	this := OutputValueAnyOf12{}
	return &this
}

// GetStatus returns the Status field value
func (o *OutputValueAnyOf12) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf12) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OutputValueAnyOf12) SetStatus(v string) {
	o.Status = v
}

// GetAttributeType returns the AttributeType field value
func (o *OutputValueAnyOf12) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *OutputValueAnyOf12) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *OutputValueAnyOf12) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o OutputValueAnyOf12) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputValueAnyOf12) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *OutputValueAnyOf12) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"attribute_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputValueAnyOf12 := _OutputValueAnyOf12{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputValueAnyOf12)

	if err != nil {
		return err
	}

	*o = OutputValueAnyOf12(varOutputValueAnyOf12)

	return err
}

type NullableOutputValueAnyOf12 struct {
	value *OutputValueAnyOf12
	isSet bool
}

func (v NullableOutputValueAnyOf12) Get() *OutputValueAnyOf12 {
	return v.value
}

func (v *NullableOutputValueAnyOf12) Set(val *OutputValueAnyOf12) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputValueAnyOf12) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputValueAnyOf12) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputValueAnyOf12(val *OutputValueAnyOf12) *NullableOutputValueAnyOf12 {
	return &NullableOutputValueAnyOf12{value: val, isSet: true}
}

func (v NullableOutputValueAnyOf12) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputValueAnyOf12) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


