/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2ListsListEntriesQueryPost200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ListsListEntriesQueryPost200ResponseDataInner{}

// V2ListsListEntriesQueryPost200ResponseDataInner struct for V2ListsListEntriesQueryPost200ResponseDataInner
type V2ListsListEntriesQueryPost200ResponseDataInner struct {
	Id V2ListsListEntriesQueryPost200ResponseDataInnerId `json:"id"`
	// A UUID identifying the record that is parent of the list entry.
	ParentRecordId string `json:"parent_record_id"`
	// A UUID or slug identifying the object that the parent record belongs to.
	ParentObject string `json:"parent_object"`
	// When this entry was created.
	CreatedAt string `json:"created_at"`
	// A list of attribute values for the list entry (not attribute values for its parent record).
	EntryValues map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner `json:"entry_values"`
}

type _V2ListsListEntriesQueryPost200ResponseDataInner V2ListsListEntriesQueryPost200ResponseDataInner

// NewV2ListsListEntriesQueryPost200ResponseDataInner instantiates a new V2ListsListEntriesQueryPost200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ListsListEntriesQueryPost200ResponseDataInner(id V2ListsListEntriesQueryPost200ResponseDataInnerId, parentRecordId string, parentObject string, createdAt string, entryValues map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) *V2ListsListEntriesQueryPost200ResponseDataInner {
	this := V2ListsListEntriesQueryPost200ResponseDataInner{}
	this.Id = id
	this.ParentRecordId = parentRecordId
	this.ParentObject = parentObject
	this.CreatedAt = createdAt
	this.EntryValues = entryValues
	return &this
}

// NewV2ListsListEntriesQueryPost200ResponseDataInnerWithDefaults instantiates a new V2ListsListEntriesQueryPost200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ListsListEntriesQueryPost200ResponseDataInnerWithDefaults() *V2ListsListEntriesQueryPost200ResponseDataInner {
	this := V2ListsListEntriesQueryPost200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetId() V2ListsListEntriesQueryPost200ResponseDataInnerId {
	if o == nil {
		var ret V2ListsListEntriesQueryPost200ResponseDataInnerId
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetIdOk() (*V2ListsListEntriesQueryPost200ResponseDataInnerId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) SetId(v V2ListsListEntriesQueryPost200ResponseDataInnerId) {
	o.Id = v
}

// GetParentRecordId returns the ParentRecordId field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetParentRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentRecordId
}

// GetParentRecordIdOk returns a tuple with the ParentRecordId field value
// and a boolean to check if the value has been set.
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetParentRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentRecordId, true
}

// SetParentRecordId sets field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) SetParentRecordId(v string) {
	o.ParentRecordId = v
}

// GetParentObject returns the ParentObject field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetParentObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentObject
}

// GetParentObjectOk returns a tuple with the ParentObject field value
// and a boolean to check if the value has been set.
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetParentObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentObject, true
}

// SetParentObject sets field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) SetParentObject(v string) {
	o.ParentObject = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetEntryValues returns the EntryValues field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetEntryValues() map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner {
	if o == nil {
		var ret map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner
		return ret
	}

	return o.EntryValues
}

// GetEntryValuesOk returns a tuple with the EntryValues field value
// and a boolean to check if the value has been set.
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) GetEntryValuesOk() (map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner, bool) {
	if o == nil {
		return map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner{}, false
	}
	return o.EntryValues, true
}

// SetEntryValues sets field value
func (o *V2ListsListEntriesQueryPost200ResponseDataInner) SetEntryValues(v map[string][]V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) {
	o.EntryValues = v
}

func (o V2ListsListEntriesQueryPost200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ListsListEntriesQueryPost200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["parent_record_id"] = o.ParentRecordId
	toSerialize["parent_object"] = o.ParentObject
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["entry_values"] = o.EntryValues
	return toSerialize, nil
}

func (o *V2ListsListEntriesQueryPost200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"parent_record_id",
		"parent_object",
		"created_at",
		"entry_values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2ListsListEntriesQueryPost200ResponseDataInner := _V2ListsListEntriesQueryPost200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ListsListEntriesQueryPost200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = V2ListsListEntriesQueryPost200ResponseDataInner(varV2ListsListEntriesQueryPost200ResponseDataInner)

	return err
}

type NullableV2ListsListEntriesQueryPost200ResponseDataInner struct {
	value *V2ListsListEntriesQueryPost200ResponseDataInner
	isSet bool
}

func (v NullableV2ListsListEntriesQueryPost200ResponseDataInner) Get() *V2ListsListEntriesQueryPost200ResponseDataInner {
	return v.value
}

func (v *NullableV2ListsListEntriesQueryPost200ResponseDataInner) Set(val *V2ListsListEntriesQueryPost200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ListsListEntriesQueryPost200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ListsListEntriesQueryPost200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ListsListEntriesQueryPost200ResponseDataInner(val *V2ListsListEntriesQueryPost200ResponseDataInner) *NullableV2ListsListEntriesQueryPost200ResponseDataInner {
	return &NullableV2ListsListEntriesQueryPost200ResponseDataInner{value: val, isSet: true}
}

func (v NullableV2ListsListEntriesQueryPost200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ListsListEntriesQueryPost200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


