/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// V2MeetingsPostRequestDataParticipantsInnerIsOrganizer Whether or not the participant is the organizer of the meeting.
type V2MeetingsPostRequestDataParticipantsInnerIsOrganizer struct {
	Bool *bool
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2MeetingsPostRequestDataParticipantsInnerIsOrganizer) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Bool
	err = json.Unmarshal(data, &dst.Bool);
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			return nil // data stored in dst.Bool, return on the first match
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2MeetingsPostRequestDataParticipantsInnerIsOrganizer)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2MeetingsPostRequestDataParticipantsInnerIsOrganizer) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer struct {
	value *V2MeetingsPostRequestDataParticipantsInnerIsOrganizer
	isSet bool
}

func (v NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer) Get() *V2MeetingsPostRequestDataParticipantsInnerIsOrganizer {
	return v.value
}

func (v *NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer) Set(val *V2MeetingsPostRequestDataParticipantsInnerIsOrganizer) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer(val *V2MeetingsPostRequestDataParticipantsInnerIsOrganizer) *NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer {
	return &NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer{value: val, isSet: true}
}

func (v NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MeetingsPostRequestDataParticipantsInnerIsOrganizer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


