/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NoteTagsInnerOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoteTagsInnerOneOf1{}

// NoteTagsInnerOneOf1 struct for NoteTagsInnerOneOf1
type NoteTagsInnerOneOf1 struct {
	// The type of entity tagged in the note. Can be either 'workspace-member' or 'record'
	Type string `json:"type"`
	// The slug or ID of the object that the tagged record belongs to.
	Object string `json:"object"`
	// The ID of the record that is tagged in the note.
	RecordId string `json:"record_id"`
}

type _NoteTagsInnerOneOf1 NoteTagsInnerOneOf1

// NewNoteTagsInnerOneOf1 instantiates a new NoteTagsInnerOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoteTagsInnerOneOf1(type_ string, object string, recordId string) *NoteTagsInnerOneOf1 {
	this := NoteTagsInnerOneOf1{}
	this.Type = type_
	this.Object = object
	this.RecordId = recordId
	return &this
}

// NewNoteTagsInnerOneOf1WithDefaults instantiates a new NoteTagsInnerOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoteTagsInnerOneOf1WithDefaults() *NoteTagsInnerOneOf1 {
	this := NoteTagsInnerOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *NoteTagsInnerOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NoteTagsInnerOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NoteTagsInnerOneOf1) SetType(v string) {
	o.Type = v
}

// GetObject returns the Object field value
func (o *NoteTagsInnerOneOf1) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *NoteTagsInnerOneOf1) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *NoteTagsInnerOneOf1) SetObject(v string) {
	o.Object = v
}

// GetRecordId returns the RecordId field value
func (o *NoteTagsInnerOneOf1) GetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value
// and a boolean to check if the value has been set.
func (o *NoteTagsInnerOneOf1) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordId, true
}

// SetRecordId sets field value
func (o *NoteTagsInnerOneOf1) SetRecordId(v string) {
	o.RecordId = v
}

func (o NoteTagsInnerOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoteTagsInnerOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["object"] = o.Object
	toSerialize["record_id"] = o.RecordId
	return toSerialize, nil
}

func (o *NoteTagsInnerOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"object",
		"record_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNoteTagsInnerOneOf1 := _NoteTagsInnerOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNoteTagsInnerOneOf1)

	if err != nil {
		return err
	}

	*o = NoteTagsInnerOneOf1(varNoteTagsInnerOneOf1)

	return err
}

type NullableNoteTagsInnerOneOf1 struct {
	value *NoteTagsInnerOneOf1
	isSet bool
}

func (v NullableNoteTagsInnerOneOf1) Get() *NoteTagsInnerOneOf1 {
	return v.value
}

func (v *NullableNoteTagsInnerOneOf1) Set(val *NoteTagsInnerOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteTagsInnerOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteTagsInnerOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteTagsInnerOneOf1(val *NoteTagsInnerOneOf1) *NullableNoteTagsInnerOneOf1 {
	return &NullableNoteTagsInnerOneOf1{value: val, isSet: true}
}

func (v NullableNoteTagsInnerOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteTagsInnerOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


