/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2NotesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2NotesPostRequest{}

// V2NotesPostRequest struct for V2NotesPostRequest
type V2NotesPostRequest struct {
	Data V2NotesPostRequestData `json:"data"`
}

type _V2NotesPostRequest V2NotesPostRequest

// NewV2NotesPostRequest instantiates a new V2NotesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2NotesPostRequest(data V2NotesPostRequestData) *V2NotesPostRequest {
	this := V2NotesPostRequest{}
	this.Data = data
	return &this
}

// NewV2NotesPostRequestWithDefaults instantiates a new V2NotesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2NotesPostRequestWithDefaults() *V2NotesPostRequest {
	this := V2NotesPostRequest{}
	return &this
}

// GetData returns the Data field value
func (o *V2NotesPostRequest) GetData() V2NotesPostRequestData {
	if o == nil {
		var ret V2NotesPostRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V2NotesPostRequest) GetDataOk() (*V2NotesPostRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V2NotesPostRequest) SetData(v V2NotesPostRequestData) {
	o.Data = v
}

func (o V2NotesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2NotesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *V2NotesPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2NotesPostRequest := _V2NotesPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2NotesPostRequest)

	if err != nil {
		return err
	}

	*o = V2NotesPostRequest(varV2NotesPostRequest)

	return err
}

type NullableV2NotesPostRequest struct {
	value *V2NotesPostRequest
	isSet bool
}

func (v NullableV2NotesPostRequest) Get() *V2NotesPostRequest {
	return v.value
}

func (v *NullableV2NotesPostRequest) Set(val *V2NotesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2NotesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2NotesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2NotesPostRequest(val *V2NotesPostRequest) *NullableV2NotesPostRequest {
	return &NullableV2NotesPostRequest{value: val, isSet: true}
}

func (v NullableV2NotesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2NotesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


